notARepository: skip
gui:
  screenMode: full
quitOnTopLevelReturn: true
nerdFontsVersion: 3
git:
  localBranchSortOrder: recency
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
