[colors]
# Oldworld Cooler - Dark theme with relaxing and no-saturated colors
# Cooler variant

# Basic colors
foreground = "#c8c7cd"
background = "#161617"
cursor_bg = "#c8c7cd"
cursor_fg = "#161617"
cursor_border = "#c8c7cd"

# Selection colors
selection_bg = "#2a2b2c"
selection_fg = "#c8c7cd"

# Scrollbar colors
scrollbar_thumb = "#313234"

# Split/pane colors
split = "#444448"

# Tab bar colors
[colors.tab_bar]
background = "#161617"

[colors.tab_bar.active_tab]
bg_color = "#2a2b2c"
fg_color = "#c8c7cd"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#18181a"
fg_color = "#888693"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1b1b1c"
fg_color = "#b2b1ba"

[colors.tab_bar.new_tab]
bg_color = "#161617"
fg_color = "#696874"

[colors.tab_bar.new_tab_hover]
bg_color = "#18181a"
fg_color = "#9c9ca6"

# ANSI colors (0-7)
[colors.ansi]
black = "#27282a"
red = "#ea83bf"
green = "#90b995"
yellow = "#e6a79d"
blue = "#92b3d5"
magenta = "#a1a1cf"
cyan = "#85bab2"
white = "#c8c7cd"

# Bright ANSI colors (8-15)
[colors.brights]
black = "#696874"
red = "#ea83bf"
green = "#90b995"
yellow = "#e6a79d"
blue = "#92b3d5"
magenta = "#e29edb"
cyan = "#85bab2"
white = "#c8c7cd"

# Extended colors for better 256-color support
[colors.indexed]
"16" = "#f5919a"  # orange
"17" = "#e29edb"  # bright magenta
"18" = "#18181a"  # gray0
"19" = "#1b1b1c"  # gray1
"20" = "#2a2b2c"  # gray2
"21" = "#313234"  # gray3
"22" = "#3b3c3e"  # gray4
"23" = "#444448"  # gray5
"24" = "#696874"  # subtext4
"25" = "#888693"  # subtext3
"26" = "#9c9ca6"  # subtext2
"27" = "#b2b1ba"  # subtext1
"28" = "#131314"  # bg_dark

[metadata]
name = "Oldworld Cooler"
