# Oldworld - Dark theme with relaxing and no-saturated colors
# Default variant
#
[colors]
ansi = [
    "#27272a",
    "#ea83a5",
    "#90b99f",
    "#e6b99d",
    "#92a2d5",
    "#aca1cf",
    "#85b5ba",
    "#c9c7cd"
]
brights = [
    "#6c6874",
    "#ea83a5",
    "#90b99f",
    "#e6b99d",
    "#92a2d5",
    "#e29eca",
    "#85b5ba",
    "#c9c7cd"
]
foreground = "#c9c7cd"
background = "#161617"
cursor_bg = "#c9c7cd"
cursor_fg = "#161617"
cursor_border = "#c9c7cd"
selection_bg = "#2a2a2c"
selection_fg = "#c9c7cd"
scrollbar_thumb = "#313134"
split = "#444448"

[colors.tab_bar]
background = "#161617"

[colors.tab_bar.active_tab]
bg_color = "#2a2a2c"
fg_color = "#c9c7cd"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "#18181a"
fg_color = "#8b8693"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1b1b1c"
fg_color = "#b4b1ba"

[colors.tab_bar.new_tab]
bg_color = "#161617"
fg_color = "#6c6874"

[colors.tab_bar.new_tab_hover]
bg_color = "#18181a"
fg_color = "#9f9ca6"
[colors.indexed]
"16" = "#f5a191"
"17" = "#e29eca"
"18" = "#18181a"
"19" = "#1b1b1c"
"20" = "#2a2a2c"
"21" = "#313134"
"22" = "#3b3b3e"
"23" = "#444448"
"24" = "#6c6874"
"25" = "#8b8693"
"26" = "#9f9ca6"
"27" = "#b4b1ba"
"28" = "#131314"

[metadata]
name = "Oldworld"
author = "Your Name"
origin_url = "https://github.com/yourusername/wezterm-oldworld-theme"
